spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false

  flyway:
    enabled: false # Desativa o Flyway durante os testes unitários/integrados com H2

app:
  jwt:
    segredo: "dGVzdGUtc2VncmVkby1qd3QtYW1pZ29zLWRvLW5vcmRlc3RlLXRhc2stMjA=" # Chave base64 >= 32 bytes
    validade-acesso: 15m
    validade-renovacao: 7d
  cookie-seguro: false
